// UI Map schemas and types
export {
  UIElementRoleSchema,
  BBoxSchema,
  NeighborsSchema,
  ElementSignatureSchema,
  UIElementSchema,
  ScreenMetadataSchema,
  UIMapSchema,
  ParseRequestSchema,
  ParseResponseSchema,
  type UIElementRole,
  type BBox,
  type Neighbors,
  type ElementSignature,
  type UIElement,
  type ScreenMetadata,
  type UIMap,
  type ParseRequest,
  type ParseResponse,
  // Utility functions
  getElementCenter,
  bboxOverlaps,
  normalizeBbox,
  findElementById,
  findElementsByRole,
  findInteractableElements,
  findElementByText,
} from './schemas/ui-map.js';

// Action schemas and types
export {
  ActionTypeSchema,
  AssertPredicateKindSchema,
  AssertPredicateSchema,
  ScrollDirectionSchema,
  TestActionSchema,
  HealingConfigSchema,
  TestStepSchema,
  TestSuiteMetadataSchema,
  TestSuiteSchema,
  ActionResultStatusSchema,
  ActionResultSchema,
  StepResultSchema,
  type ActionType,
  type AssertPredicateKind,
  type AssertPredicate,
  type ScrollDirection,
  type TestAction,
  type HealingConfig,
  type TestStep,
  type TestSuiteMetadata,
  type TestSuite,
  type ActionResultStatus,
  type ActionResult,
  type StepResult,
  // Helper functions
  click,
  type as typeAction,
  wait,
  assertTextExists,
  assertElementExists,
  navigate,
  hover,
  pressKey,
} from './schemas/action.js';

// Trajectory schemas and types
export {
  HealingEventSchema,
  DriftAlertSchema,
  TrajectoryEntrySchema,
  TestRunMetadataSchema,
  TestRunSummarySchema,
  TrajectoryLogSchema,
  TrajectoryConfigSchema,
  type HealingEvent,
  type DriftAlert,
  type TrajectoryEntry,
  type TestRunMetadata,
  type TestRunSummary,
  type TrajectoryLog,
  type TrajectoryConfig,
  // Helper functions
  generateRunId,
  generateEntryId,
  calculateSummary,
  formatDuration,
} from './schemas/trajectory.js';

